/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CategoryItem: typeof import('./modules/categories/components/CategoryItem.vue')['default']
    CategoryList: typeof import('./modules/categories/components/CategoryList.vue')['default']
    ContactForm: typeof import('./modules/checkout/components/ContactForm.vue')['default']
    FormLabel: typeof import('./modules/checkout/components/FormLabel.vue')['default']
    InputContainer: typeof import('./modules/checkout/components/InputContainer.vue')['default']
    OrderSummary: typeof import('./modules/checkout/components/OrderSummary.vue')['default']
    PageActions: typeof import('./components/PageActions.vue')['default']
    PrimaryAction: typeof import('./components/PrimaryAction.vue')['default']
    PrimaryLink: typeof import('./components/PrimaryLink.vue')['default']
    ProductItem: typeof import('./modules/categories/components/ProductItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryAction: typeof import('./components/SecondaryAction.vue')['default']
    SecondaryLink: typeof import('./components/SecondaryLink.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    SubHeading: typeof import('./components/SubHeading.vue')['default']
  }
}
